### ISSUE TITLE
Create Interview Template

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/starlight-legacy#56]
<img width="838" alt="image" src="https://github.com/user-attachments/assets/5e37662a-7dcf-43b7-8d22-f898914767ed">

- Should be added to the bottom of the form
- Should integrate shadcn calendar, dont need to worry bout the data working and everything, as long as the calendar is available you should be good to go

**Comment by zenxha** [comment]
<img width="860" alt="Screenshot 2024-11-19 at 12 12 29 AM" src="https://github.com/user-attachments/assets/9aa90e0d-8ab1-4f34-a433-43ff16cf30ab">
<img width="865" alt="Screenshot 2024-11-19 at 12 12 52 AM" src="https://github.com/user-attachments/assets/a3ba2c07-d98f-4ff7-852a-9efac71433ff">

Should I follow the screenshot's color scheme or should i keep it consistent with the rest of the form (above the calendar)

**Comment by seanquiambao** [comment]
still working on issue ^

**Comment by zenxha** [comment]
<img width="863" alt="Screenshot 2024-11-25 at 6 27 33 PM" src="https://github.com/user-attachments/assets/5fc41520-6a28-4a55-b32a-6eb62fb19a11">
