### ISSUE TITLE
Change To Trash and Refresh Icons

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/starlight-legacy#62]
<img width="221" alt="image" src="https://github.com/user-attachments/assets/730c0bc8-acb1-4b9d-ba17-80565eefb0cd">

- Use Lucide Icons and replace the text

**Comment by patricksolka** [comment]
Hey @shahdivyank could you tell me the page this is related to? I will fix this! Could you assign it to me?

**Comment by AnPhu-D** [comment]
![image](https://github.com/user-attachments/assets/eae55e44-001d-45e6-91b4-e35b4404edf8)
