### ISSUE TITLE
Add conditional rendering to input.tsx

### ISSUE THREAD

**Issue by AnPhu-D** [acm-ucr/starlight-legacy#68]
Currently, creating an input component with an empty title will create a 0-size label and place a gap-3 above the input field.

Intended (and correct) current behavior: See the /form/director page as an example of where the Input component is used.
http://localhost:3000/form/director

Unintended behavior: See the /admin/ignite/application page as an example of where the gap-3 is harmful
http://localhost:3000/admin/ignite/application

Ask:
Make it so the label component (which is part of the input component) is conditionally rendered.
- When title is empty, do not render label component.
- Otherwise, render as usual.

**Comment by shahdivyank** [comment]
Issues are to only be created by Sean, Andrew and Divyank
