### ISSUE TITLE
Search Functionality Table

### ISSUE THREAD

**Issue by seanquiambao** [acm-ucr/starlight-legacy#94]
<img width="784" alt="image" src="https://github.com/user-attachments/assets/fae9ca94-9890-42ac-a0d8-62e8255020bb">

When you type in Divyank in the search bar, it should filter out all Andrew's data.

Refer to hackathon-website

**Comment by AnPhu-D** [comment]
![image](https://github.com/user-attachments/assets/948dc9ab-52f0-4e8b-8102-bcf0fe002480)

**Comment by AnPhu-D** [comment]
![image](https://github.com/user-attachments/assets/180e866b-f6af-4308-8ea2-5b87814207f3)

**Comment by AnPhu-D** [comment]
Filters on any field of the row entry, not just name.
